version: '3.8'
services:
  php:
    build: ./
    volumes:
      - ./:/var/www/phones-validations
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
  web:
    image: nginx:latest
    ports:
      - "8880:80"
    volumes:
      - ./:/var/www/phones-validations
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
networks:
  app-network:
    driver: bridge



